---
- name: Ensure Traefik config.
  template:
    src: traefik.yml.j2
    dest: "{{ hms_docker_apps_path }}/traefik/config/traefik.yml"
    mode: 0644
    group: docker
    backup: yes
  notify: restart traefik

- name: Ensure Traefik certs directory
  file:
    path: "{{ hms_docker_apps_path }}/traefik/config/certs"
    state: directory
  register: traefik_certs_dir
