---
### Any variables such as "{{ <variable> }}" will reference a variable that was defined earlier in this file


#######################################################################
### hosts Settings
hostname: hms-prod.kr1ps.com
hostname_short: hms-prod
tmzone: America/Santo_Domingo

### End of hosts Settings
#######################################################################

#######################################################################
### Plex Settings
# Visit https://plex.tv/claim to obtain this token specific to your account
plex_claim_token: ""

### End of Plex Settings
#######################################################################

#######################################################################
### Docker Role vars settings

docker_users:
  - krips

tf-env: "{{ lookup('vars', tf_environment) }}"

### End of Docker Role vars settings
#######################################################################

#######################################################################
### HMS-Docker settings

# Where the media share will be mounted locally // default: "/opt/{{ project_name }}/media_data"
# Recommended to change this if using `cifs` or `nfs` to a local mount point, such as "/mnt/{{ project_name }}"
hms_docker_mount_path: "/opt/{{ project_name }}/media_data"

# The domain used for the Traefik proxy Host rules, SSL certificate (if enabled), and DDNS (if enabled) // default: "home.local"
hms_docker_domain: kr1ps.com

### End of HMS-Docker settings
#######################################################################


#######################################################################
### Container settings

# Enables the "watchtower" container to automatically download and apply container updates // default: "yes"
container_enable_auto_updates: yes

# The timezone to use for the containers // default: "America/Santo_Domingo"
container_timezone: America/Santo_Domingo

# User and Group ID's to use for the running processes in the containers (may cause or be the cause of permissions issues)
#  default: "1234"
container_uid: 1234
container_gid: 1234

### End of Container settings
#######################################################################


#######################################################################
### Cloudflare DDNS settings
# Enables or disables the Cloudflare DDNS container // default: "no"
cloudflare_ddns_enabled: no

# Your Cloudflare API token that has read/write permissions for your DNS zone
cloudflare_api_token: ""

# The domain that will be used for the Cloudflare DDNS container // default: "{{ hms_docker_domain }}"
# Automatically uses the same domain defined above
cloudflare_ddns_domain: "{{ hms_docker_domain }}"

# The A (or AAAA) record to be created // default: "overseerr"
# May cause issues if not set to "overseerr" due to the Traefik Host rules
cloudflare_ddns_subdomain: overseerr

### End of Cloudflare DDNS settings
#######################################################################

#######################################################################
### SSL and Traefik settings
# Enables or Disables SSL wildcard certificate generation // default: "no"
traefik_ssl_enabled: yes

# Whether to use the staging/testing URL or production URL // default: "yes"
# If SSL is enabled and this is set to yes, check to make sure the generated certificate is issued from the "STAGING" certificate authority before changing this to "no"
traefik_ssl_use_letsencrypt_staging_url: yes

# The DNS provider to use for SSL generation, check this for supported providers: https://doc.traefik.io/traefik/https/acme/#providers
traefik_ssl_dns_provider_code: ""

# The DNS zone to use for SSL generation, this will use the domain defined above // default: "{{ hms_docker_domain }}"
traefik_ssl_dns_provider_zone: "{{ hms_docker_domain }}"

# The environment variables for your DNS provider found at the provider link above
# This is an example if using Cloudflare
traefik_ssl_dns_provider_environment_vars:
  {
    "CF_DNS_API_TOKEN": "{{ cloudflare_api_token }}", # Example cloudflare environment variable, can use the same API token as the one for DDNS
    "CF_ZONE_API_TOKEN": "{{ cloudflare_api_token }}", # Example cloudflare environment variable, can use the same API token as the one for DDNS
  }

# The DNS servers to use when generating your SSL certificate
# Recommended to set to your DNS providers servers
traefik_ssl_dns_resolver_1: "1.1.1.1"
traefik_ssl_dns_resolver_2: "1.0.0.1"

# Required for Let's Encrypt, the email address to use when generating your SSL certificate
traefik_ssl_letsencrypt_email: "me@kr1ps.com"

# The Traefik Pilot token (only available after first run)
traefik_pilot_token: ""
### End of SSL and Traefik settings
#######################################################################




