---
- name: hms-setup.
  hosts: all
  become: true

  vars_files:
    - ./vars/default.yml

  roles:
    - host-config1
    - docker
    - host-netconfig1


  handlers:


  pre_tasks:

  tasks:
    - name: Ping
      ping:
    # Host Setup

