---
- name: hms-setup.
  hosts: all
  become: true
  vars:
    regex: '[^A-Za-z0-9._-]'
    replace: '_'

  vars_files:
    - ./vars/default.yml

  roles:
    - docker
    #- host-config1
    #- host-netconfig1


  handlers:


  pre_tasks:

  tasks:
    - name: Ping
      ping:


    - name: Ensure kr1ps-Docker role
      import_role:
        name: kr1ps-services

    - name: Verify all Traefik endpoints are accessible
      uri:
        url: http://{{ item.key }}.{{ hms_docker_domain }}
        status_code: 200,302,401,403
        validate_certs: no
      with_dict:
        - "{{ hms_docker_container_map }}"
      when:
        - item.value.traefik is defined and item.value.traefik
        - item.value.enabled is defined and item.value.enabled
        - hms_docker_container_map['traefik']['enabled'] is defined and hms_docker_container_map['traefik']['enabled']
        - traefik_verify_endpoints is defined and traefik_verify_endpoints

