---
- name: restart traefik
  shell: docker restart traefik
  when: not traefik_certs_dir.changed


- name: ensure plex
  docker_compose:
    project_src: "{{ hms_docker_data_path }}"
    project_name: "{{ project_name }}"
    pull: "{{ container_pull_images_first }}"
    state: "{{ hms_docker_compose_container_state }}"
    remove_orphans: "{{ container_remove_orphans }}"